In [2]:
# ==========================================
# Customer Churn Intelligence Platform
# Exploratory Data Analysis (EDA)
# ==========================================

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import plotly.express as px

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
# Load dataset
df = pd.read_excel("../data/raw/Telco_customer_churn.xlsx")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [4]:
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,No,No,Yes,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,No,No,Yes,49,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [5]:
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 7043
Columns: 33

In [6]:
df.columns.tolist()

['CustomerID',
 'Count',
 'Country',
 'State',
 'City',
 'Zip Code',
 'Lat Long',
 'Latitude',
 'Longitude',
 'Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'Tenure Months',
 'Phone Service',
 'Multiple Lines',
 'Internet Service',
 'Online Security',
 'Online Backup',
 'Device Protection',
 'Tech Support',
 'Streaming TV',
 'Streaming Movies',
 'Contract',
 'Paperless Billing',
 'Payment Method',
 'Monthly Charges',
 'Total Charges',
 'Churn Label',
 'Churn Value',
 'Churn Score',
 'CLTV',
 'Churn Reason']

In [7]:
df.dtypes

CustomerID               str
Count                  int64
Country                  str
State                    str
City                     str
Zip Code               int64
Lat Long                 str
Latitude             float64
Longitude            float64
Gender                   str
Senior Citizen           str
Partner                  str
Dependents               str
Tenure Months          int64
Phone Service            str
Multiple Lines           str
Internet Service         str
Online Security          str
Online Backup            str
Device Protection        str
Tech Support             str
Streaming TV             str
Streaming Movies         str
Contract                 str
Paperless Billing        str
Payment Method           str
Monthly Charges      float64
Total Charges         object
Churn Label              str
Churn Value            int64
Churn Score            int64
CLTV                   int64
Churn Reason             str
dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   str
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   str
 3   State              7043 non-null   str
 4   City               7043 non-null   str
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   str
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   str
 10  Senior Citizen     7043 non-null   str
 11  Partner            7043 non-null   str
 12  Dependents         7043 non-null   str
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   str
 15  Multiple Lines     7043 non-null   str
 16  Internet Service   7043 non-null   str
 17  Online Security    7043 non-null   str
 18  Online Backup      7043 non-null   str
 19  Device Protection  7043 non-null   str
 20  Tech Support       7043 non-null   str
 21  Streaming TV       7043 non-null   str
 22  Streaming Movies   7043 non-null   str
 23  Contract           7043 non-null   str
 24  Paperless Billing  7043 non-null   str
 25  Payment Method     7043 non-null   str
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   str
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   str
dtypes: float64(3), int64(6), object(1), str(23)
memory usage: 1.8+ MB

# Data Quality Assessment

In [9]:
# Missing Values
missing_df = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().mean()*100).round(2)
})

missing_df = missing_df[missing_df["Missing Values"] > 0]

missing_df.sort_values(
    by="Missing Values",
    ascending=False
)

              Missing Values  Percentage
Churn Reason            5174       73.46

In [10]:
# Duplicate Records
duplicates = df.duplicated().sum()

print(f"Duplicate Rows: {duplicates}")

Duplicate Rows: 0

In [11]:
# Unique Values
df.nunique().sort_values()

Count                   1
Country                 1
State                   1
Phone Service           2
Dependents              2
Partner                 2
Senior Citizen          2
Gender                  2
Churn Value             2
Paperless Billing       2
Churn Label             2
Multiple Lines          3
Internet Service        3
Online Backup           3
Online Security         3
Tech Support            3
Contract                3
Streaming Movies        3
Streaming TV            3
Device Protection       3
Payment Method          4
Churn Reason           20
Tenure Months          73
Churn Score            85
City                 1129
Monthly Charges      1585
Longitude            1651
Latitude             1652
Lat Long             1652
Zip Code             1652
CLTV                 3438
Total Charges        6531
CustomerID           7043
dtype: int64

In [12]:
# Constant Columns
constant_columns = [
    col
    for col in df.columns
    if df[col].nunique() == 1
]

constant_columns

['Count', 'Country', 'State']

In [13]:
# Hight Cardinality
df.nunique().sort_values(ascending=False)

CustomerID           7043
Total Charges        6531
CLTV                 3438
Lat Long             1652
Latitude             1652
Zip Code             1652
Longitude            1651
Monthly Charges      1585
City                 1129
Churn Score            85
Tenure Months          73
Churn Reason           20
Payment Method          4
Online Backup           3
Online Security         3
Multiple Lines          3
Internet Service        3
Tech Support            3
Contract                3
Streaming Movies        3
Streaming TV            3
Device Protection       3
Senior Citizen          2
Partner                 2
Dependents              2
Gender                  2
Paperless Billing       2
Churn Label             2
Phone Service           2
Churn Value             2
Count                   1
Country                 1
State                   1
dtype: int64

In [14]:
feature_inventory = pd.DataFrame({
    "Feature": df.columns,
    "Data Type": df.dtypes.astype(str).values,
    "Unique Values": [df[col].nunique() for col in df.columns],
    "Missing Values": [df[col].isnull().sum() for col in df.columns]
})

feature_inventory

              Feature Data Type  Unique Values  Missing Values
0          CustomerID       str           7043               0
1               Count     int64              1               0
2             Country       str              1               0
3               State       str              1               0
4                City       str           1129               0
5            Zip Code     int64           1652               0
6            Lat Long       str           1652               0
7            Latitude   float64           1652               0
8           Longitude   float64           1651               0
9              Gender       str              2               0
10     Senior Citizen       str              2               0
11            Partner       str              2               0
12         Dependents       str              2               0
13      Tenure Months     int64             73               0
14      Phone Service       str              2               0
15     Multiple Lines       str              3               0
16   Internet Service       str              3               0
17    Online Security       str              3               0
18      Online Backup       str              3               0
19  Device Protection       str              3               0
20       Tech Support       str              3               0
21       Streaming TV       str              3               0
22   Streaming Movies       str              3               0
23           Contract       str              3               0
24  Paperless Billing       str              2               0
25     Payment Method       str              4               0
26    Monthly Charges   float64           1585               0
27      Total Charges    object           6531               0
28        Churn Label       str              2               0
29        Churn Value     int64              2               0
30        Churn Score     int64             85               0
31               CLTV     int64           3438               0
32       Churn Reason       str             20            5174

In [15]:
feature_classification = pd.DataFrame({
    "Feature": [
        "CustomerID","Count","Country","State","City","Zip Code",
        "Lat Long","Latitude","Longitude","Gender","Senior Citizen",
        "Partner","Dependents","Tenure Months","Phone Service",
        "Multiple Lines","Internet Service","Online Security",
        "Online Backup","Device Protection","Tech Support",
        "Streaming TV","Streaming Movies","Contract",
        "Paperless Billing","Payment Method","Monthly Charges",
        "Total Charges","CLTV","Churn Score",
        "Churn Reason","Churn Value","Churn Label"
    ],
    "Category": [
        "Identifier","Constant","Constant","Constant","Geographic","Geographic",
        "Redundant","Geographic","Geographic","Categorical","Categorical",
        "Categorical","Categorical","Numerical","Categorical",
        "Categorical","Categorical","Categorical",
        "Categorical","Categorical","Categorical",
        "Categorical","Categorical","Categorical",
        "Categorical","Categorical","Numerical",
        "Numerical","Business Metric","Leakage",
        "Leakage","Target (Numeric)","Target"
    ]
})

feature_classification

              Feature          Category
0          CustomerID        Identifier
1               Count          Constant
2             Country          Constant
3               State          Constant
4                City        Geographic
5            Zip Code        Geographic
6            Lat Long         Redundant
7            Latitude        Geographic
8           Longitude        Geographic
9              Gender       Categorical
10     Senior Citizen       Categorical
11            Partner       Categorical
12         Dependents       Categorical
13      Tenure Months         Numerical
14      Phone Service       Categorical
15     Multiple Lines       Categorical
16   Internet Service       Categorical
17    Online Security       Categorical
18      Online Backup       Categorical
19  Device Protection       Categorical
20       Tech Support       Categorical
21       Streaming TV       Categorical
22   Streaming Movies       Categorical
23           Contract       Categorical
24  Paperless Billing       Categorical
25     Payment Method       Categorical
26    Monthly Charges         Numerical
27      Total Charges         Numerical
28               CLTV   Business Metric
29        Churn Score           Leakage
30       Churn Reason           Leakage
31        Churn Value  Target (Numeric)
32        Churn Label            Target